name: Deploy To Ec2

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: self-hosted
    steps:
      - name: SSh(원격 접속)로 EC2 접속
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd /home/ec2-user/always-together
            git pull origin main
            ./gradlew build -x test  # 테스트 제외하고 빌드
            sudo fuser -k -n tcp 8080 || true 
            nohup java -Xmx512m -jar build/libs/proj-lee-0.0.1-SNAPSHOT.jar --spring.profiles.active=dev > /dev/null 2>&1 & disown